#!/usr/bin/env python3
# Author: Joshua Chen
# Date: 2015-12-26
# Location: Shenzhen
# Desc: clone a repository, initialize the shadow git,
# decrypt the cipher branches.

import os, sys
prog_path = os.path.realpath(__file__)
prog_dir  = os.path.dirname(prog_path)
sys.path.insert(0, prog_dir)
import lib
