#!/usr/bin/env python3
# Author: Joshua Chen
# Date: 2015-12-26
# Location: Shenzhen
# Desc: decrypt a cipher branch

import os, sys
prog_path = os.path.realpath(__file__)
prog_dir  = os.path.dirname(prog_path)
sys.path.insert(0, prog_dir)
import lib


def help(ofile=sys.stdout):
    """ Show help message
    """
    bname = os.path.basename(sys.argv[0])
    msg =  'Usage: %s <cipher-branch> <plain-branch>' % bname
    print(msg, file=ofile)


if __name__ == '__main__':
    if not lib.env_ok():
        exit(1)

    if len(sys.argv) == 3:
        try:
            c_branch = sys.argv[1]
            p_branch = sys.argv[2]
            tip      = lib.decrypt_branch(c_branch)
            sha1     = lib.revision_parse(c_branch)
            reason = "move to the tip after decrypted branch %s (%s)" % (c_branch, sha1)
            lib.update_branch(p_branch, tip, reason)
            print('Update %s to %s.' % (p_branch, tip))
            exit(0)
        except KeyboardInterrupt:
            exit(1)
        except:
            exit(1)
    else:
        help(ofile=sys.stderr)
        exit(1)
