#!/usr/bin/env python3
# Author: Joshua Chen
# Date: 2015-12-05
# Location: Shenzhen
# Desc: secure data before pushing it to the remote,
# it pushes one branch at a time.

import os, sys
import lib

class Pusher():
    """ finds out all commits created since the last secure-push in the given
    branch, for each and every commit, do this: archive all objects of one
    single commit, encrypt it, save it to a blob object, create a tree for it,
    then a commit, the file name, author info are all faked. All encrypted
    commits are in a totally separated branch named like this: cipher-master.
    After transforming all plaintext commits into ciphertext, call the git-push
    to do the actual push.
    """

    def __init__(self, remote, branch):
        self.remote             = remote
        self.branch             = branch
        self.cipher_branch      = 'cipher-' + branch
        last_pushed             = lib.get_last_pushed(branch)
        self.last_pushed_plain  = last_pushed[0]
        self.last_pushed_cipher = last_pushed[1]
        self.new_objects        = []
        self.transformed        = False
        self.transform()
        self.push()

    def transform(self):
        """ Transform plaintext commits into one ciphertext commit, including
        all objects directly or indirectly referenced by the commits;
        create or update the cipher branch to point to the newly created
        cipher commit; encrypt the symmetric key and create a new tag for it.
        """
        commits = lib.find_all_commits(self.last_pushed_plain, self.branch)
        if not commits: return
        parent = self.last_pushed_cipher
        name   = lib.dense_time_str() + '.tar.gpg'
        dname  = name
        fname  = name + '.tar.gpg'
        tname  = 'symkey-' + name
        key    = lib.generate_key()
        for commit in commits:
            lib.copy_out_objects(commit, topdir=dname)
        blob        = lib.encrypt_path(dname, key)
        tree        = lib.create_tree(blob, fname, base=parent)
        message     = 'CIPHER COMMIT\n\nTop: %s\nBot: %s\n' % (commits[-1], commits[0])
        new_commit  = lib.create_commit(tree, parent, message)
        self.new_objects.extend([new_commit, tree, blob])
        lib.update_cipher_branch(self.cipher_branch, new_commit)
        self.cipher_key_tag       = lib.secure_key(key, tname)
        self.transformed          = True
        self.newest_plain_commit  = commits[-1]
        self.newest_cipher_commit = new_commit
        lib.cleanup(dname)

    def push(self):
        """ Push the transformed (encrypted) branch to the remote, update
        the last-pushed record mapping for the plain and cipher on success,
        reset the cipher branch back to the last pushed on failure.
        """
        if not self.transformed: return
        lib.update_cipher_branch(self.cipher_branch, self.newest_cipher_commit)
        if lib.push(self.remote, self.cipher_branch):
            lib.update_last_pushed(self.branch,
                        self.newest_plain_commit,
                        self.newest_cipher_commit)
        else:
            lib.update_cipher_branch(self.cipher_branch, self.last_pushed_cipher)
            lib.prune_objects(self.new_objects)

def help(ofile=sys.stdout):
    """ Show help message
    """
    msg = 'Usage: %s remote branch' % os.path.basename(sys.argv[0])
    print(msg, file=ofile)


if __name__ == '__main__':
    if len(sys.argv) < 3:
        help(sys.stderr)
        exit(1)

    remote, branch = sys.argv[1:3]
    if not lib.find_git_dir():
        print('Not a git repository', file=sys.stderr)
        exit(1)
    try:
        Pusher(remote, branch)
    except Exception as e:
        print(str(e))
        exit(1)
    else:
        exit(0)
